<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="网易青果接口测试"
           tests="13"
           failures="1"
           errors="0"
           skipped="0"
           time="2.301">
  <properties />
            <testcase name="addAddressSuccess" time="0.184" classname="com.edu.test.AddAddress_Test">
                <failure type="java.lang.AssertionError"
                  message="expected [success] but found [最多只能添加6个地址]"
              >
<![CDATA[java.lang.AssertionError: expected [success] but found [最多只能添加6个地址]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:453)
  org.testng.Assert.assertEquals(Assert.java:463)
  com.edu.test.AddAddress_Test.assertion(AddAddress_Test.java:23)
  com.edu.test.AddAddress_Test.addAddressSuccess(AddAddress_Test.java:40)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="addAddressFail11" time="0.092" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail7" time="0.179" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail9" time="0.189" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail5" time="0.179" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail6" time="0.187" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail10" time="0.218" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail2" time="0.176" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail1" time="0.187" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail3" time="0.174" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail4" time="0.181" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail8" time="0.177" classname="com.edu.test.AddAddress_Test" />
                <testcase name="addAddressFail0" time="0.178" classname="com.edu.test.AddAddress_Test" />
      
</testsuite>
